/* Cognitive Care NER — simple showcase authentication.
 * Uses a server-side Excel account registry. No OTP and no Supabase dependency.
 */
(()=>{'use strict';if(window.__CCNER_AUTH_V3__)return;window.__CCNER_AUTH_V3__=true;
const ENDPOINT=window.CCNER_CONFIG?.AUTH_ENDPOINT||'https://sih-prototype-repo.zopcloud.zop.dev/api/auth';let user=null,profile=null,gate=null,selectedRole='patient';
const TOKEN_KEY='ccner-local-auth-token';
const DEMO_ACCOUNTS=[
  {role:'patient',label:'Patient',loginId:'patient001',password:'Cognitive@123',icon:'🧠',description:'Mino training & progress'},
  {role:'caregiver',label:'Caregiver / Family',loginId:'caregiver001',password:'Care@1234',icon:'🤝',description:'Care plan & patient support'},
  {role:'health_worker',label:'Doctor / Health Worker',loginId:'doctor001',password:'Doctor@1234',icon:'🩺',description:'Clinical care workspace'}
];const app=()=>document.querySelector('.app-shell');const $=s=>gate?.querySelector(s);
function hideApp(){const x=app();if(x)x.style.display='none'}function showApp(){const x=app();if(x)x.style.display=''}function careRoot(){return document.querySelector('#care-dashboard-app')}function hideCare(){const x=careRoot();if(x)x.hidden=true}function showCare(){const x=careRoot();if(x)x.hidden=false}
function roleLabel(r){return r==='caregiver'?'Caregiver / Family':r==='health_worker'?'Doctor / Health Worker':'Patient'}
function msg(t){const e=$('#l2vErr');if(e){e.textContent=t||'';e.classList.toggle('show',!!t)}}
function selectRole(r){selectedRole=r;gate?.querySelectorAll('.l2v-role').forEach(b=>b.classList.toggle('selected',b.dataset.role===r));const label=roleLabel(r);const s=$('#l2vRoleStatus');if(s)s.textContent='Selected: '+label;const b=$('#l2vLogin');if(b)b.textContent='Login as '+label}
function injectCredentialStyles(){
  if(document.getElementById('ccner-demo-credentials-style'))return;
  const style=document.createElement('style');
  style.id='ccner-demo-credentials-style';
  style.textContent=`.l2v-demo-credentials{margin-top:18px;padding:16px;border:1px solid #ddd2ec;border-radius:18px;background:#f8f6ff}.l2v-demo-credentials h3{margin:0 0 5px;color:#33263a;font-size:1.05rem}.l2v-demo-credentials>p{margin:0 0 12px;color:#6f6473;font-size:.86rem;line-height:1.45}.l2v-demo-list{display:grid;gap:9px}.l2v-demo-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;padding:11px 12px;background:#fff;border:1px solid #e5dcef;border-radius:13px}.l2v-demo-icon{font-size:24px}.l2v-demo-main{min-width:0}.l2v-demo-title{font-weight:800;color:#302b3b}.l2v-demo-meta{display:flex;gap:7px;flex-wrap:wrap;margin-top:4px;font-size:.82rem;color:#5e5668}.l2v-demo-chip{display:inline-flex;align-items:center;gap:4px;background:#f0edff;border-radius:8px;padding:4px 7px}.l2v-demo-use{border:0;border-radius:10px;background:#8b7cf6;color:#fff;padding:9px 11px;font:inherit;font-weight:800;cursor:pointer;white-space:nowrap}.l2v-demo-use:hover{filter:brightness(.97)}.l2v-demo-use:focus-visible{outline:3px solid rgba(139,124,246,.3);outline-offset:2px}@media(max-width:650px){.l2v-demo-row{grid-template-columns:auto minmax(0,1fr)}.l2v-demo-use{grid-column:2;justify-self:start}}`;
  document.head.appendChild(style);
}
function useDemo(role){
  const demo=DEMO_ACCOUNTS.find(x=>x.role===role);if(!demo)return;
  selectRole(demo.role);
  const id=$('#l2vLoginId'),pw=$('#l2vPassword');
  if(id)id.value=demo.loginId;
  if(pw)pw.value=demo.password;
  msg('');
  id?.focus();
}
function render(){if(gate)return;hideApp();injectCredentialStyles();gate=document.createElement('div');gate.id='l2AuthGate';gate.innerHTML=`<div class="l2v-shell"><div class="l2v-brand"><div class="puppy">🐶</div><h1>Welcome to Cognitive Care NER</h1><p>Simple showcase login — no OTP required.</p></div><div class="l2v-card"><div class="l2v-progress"><i class="active"></i><i></i><i></i></div><div id="l2vErr" class="l2v-error" role="alert"></div><section class="l2v-step active" data-step="0"><div class="l2v-lock">🔐</div><h2>Sign in</h2><p class="hint">Choose your account type, then enter the Login ID and password provided for the showcase.</p><div class="l2v-role-picker" role="group" aria-label="Choose account role"><button type="button" class="l2v-role selected" data-role="patient"><span class="role-icon">🧠</span><strong>Patient</strong><small>Mino training &amp; progress</small></button><button type="button" class="l2v-role" data-role="caregiver"><span class="role-icon">🤝</span><strong>Caregiver / Family</strong><small>Care plan &amp; patient support</small></button><button type="button" class="l2v-role" data-role="health_worker"><span class="role-icon">🩺</span><strong>Doctor / Health Worker</strong><small>Clinical care workspace</small></button></div><div class="l2v-role-status" id="l2vRoleStatus">Selected: Patient</div><div class="l2v-field"><label for="l2vLoginId">Login ID</label><input id="l2vLoginId" autocomplete="username" placeholder="e.g. patient001"></div><div class="l2v-field"><label for="l2vPassword">Password</label><input id="l2vPassword" type="password" autocomplete="current-password" placeholder="Enter password"></div><div class="l2v-actions"><button class="l2v-btn primary" id="l2vLogin" type="button">Login as Patient</button></div><div class="l2v-demo-credentials"><h3>🎓 Demo credentials for evaluation</h3><p>These showcase accounts are ready to use. Teachers/evaluators can select <strong>Use this account</strong> to fill the Login ID and password automatically.</p><div class="l2v-demo-list">${DEMO_ACCOUNTS.map(d=>`<div class="l2v-demo-row"><span class="l2v-demo-icon">${d.icon}</span><div class="l2v-demo-main"><div class="l2v-demo-title">${d.label}</div><div class="l2v-demo-meta"><span class="l2v-demo-chip">ID: <strong>${d.loginId}</strong></span><span class="l2v-demo-chip">Password: <strong>${d.password}</strong></span></div></div><button type="button" class="l2v-demo-use" data-demo-role="${d.role}">Use this account</button></div>`).join('')}</div></div><div class="l2v-note"><strong>Showcase mode:</strong> authentication is handled by the app server and the account registry. No SMS or email OTP is required.</div><div class="l2v-note"><strong>For evaluation:</strong> use the demo credentials above. New-account creation is intentionally disabled for this showcase.</div></section></div></div>`;document.body.prepend(gate);wire()}
function wire(){gate.querySelectorAll('.l2v-role').forEach(b=>b.onclick=()=>selectRole(b.dataset.role));gate.querySelectorAll('.l2v-demo-use').forEach(b=>b.onclick=()=>useDemo(b.dataset.demoRole));$('#l2vLogin').onclick=login;$('#l2vPassword').onkeydown=e=>{if(e.key==='Enter')login()}}
async function api(path,options={}){const r=await fetch(ENDPOINT+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Authentication request failed.');return d}
function saveSession(token,p){try{localStorage.setItem(TOKEN_KEY,token);localStorage.setItem('ccner.local.profile',JSON.stringify(p))}catch{}}
function clearSession(){try{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem('ccner.local.profile')}catch{}}
async function login(){msg('');const loginId=$('#l2vLoginId')?.value.trim(),password=$('#l2vPassword')?.value;if(!loginId||!password)return msg('Enter your Login ID and password.');const b=$('#l2vLogin');b.disabled=true;b.textContent='Checking…';try{const d=await api('/login',{method:'POST',body:JSON.stringify({loginId,password,role:selectedRole})});user=d.user;profile={...d.user,user_id:d.user.user_id,display_name:d.user.full_name,requested_role:d.user.role,role:d.user.role,profile_complete:true};saveSession(d.token,profile);finish()}catch(e){msg(e.message||'Login failed.')}finally{b.disabled=false;b.textContent='Login as '+roleLabel(selectedRole)}}
async function restore(){const token=localStorage.getItem(TOKEN_KEY);if(!token){render();return}try{const d=await api('/me',{headers:{Authorization:'Bearer '+token}});user=d.user;profile={...d.user,user_id:d.user.user_id,display_name:d.user.full_name,requested_role:d.user.role,role:d.user.role,profile_complete:true};finish()}catch{clearSession();render()}}
function finish(){try{window.CCNERAuth?.__set?.(user,profile)}catch{}gate?.remove();gate=null;const careRole=['caregiver','health_worker'].includes(profile?.role);if(careRole){hideApp();showCare();window.CCNERCareDashboard?.mount?.(profile.role,profile)}else{window.CCNERCareDashboard?.unmount?.();hideCare();showApp()}window.CCNERRuleEngine?.setState({auth:'authenticated',profileComplete:true,role:profile?.role||'patient'});window.CCNERRuleEngine?.evaluate('AUTH_SUCCESS',{profileComplete:true,role:profile?.role||'patient'});window.dispatchEvent(new CustomEvent('ccner:profile-ready',{detail:{...profile,userId:user?.user_id}}))}
async function signOut(){const token=localStorage.getItem(TOKEN_KEY);try{if(token)await api('/logout',{method:'POST',headers:{Authorization:'Bearer '+token}})}catch{}clearSession();user=null;profile=null;gate?.remove();gate=null;window.CCNERCareDashboard?.unmount?.();hideCare();hideApp();render()}
function client(){return null}
window.CCNERAuth={client,getProfile:()=>profile,isAuthenticated:()=>!!user,signOut,__set:(u,p)=>{user=u;profile=p}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',restore,{once:true});else restore();
})();