/* Cognitive Care NER — simple showcase authentication.
 * Uses a server-side Excel account registry. No OTP and no Supabase dependency.
 */
(()=>{'use strict';if(window.__CCNER_AUTH_V3__)return;window.__CCNER_AUTH_V3__=true;
const ENDPOINT=window.CCNER_CONFIG?.AUTH_ENDPOINT||'https://sih-prototype-repo.zopcloud.zop.dev/api/auth';let user=null,profile=null,gate=null,selectedRole='patient';
const TOKEN_KEY='ccner-local-auth-token';const app=()=>document.querySelector('.app-shell');const $=s=>gate?.querySelector(s);
function hideApp(){const x=app();if(x)x.style.display='none'}function showApp(){const x=app();if(x)x.style.display=''}
function roleLabel(r){return r==='caregiver'?'Caregiver / Family':r==='health_worker'?'Doctor / Health Worker':'Patient'}
function msg(t){const e=$('#l2vErr');if(e){e.textContent=t||'';e.classList.toggle('show',!!t)}}
function selectRole(r){selectedRole=r;gate?.querySelectorAll('.l2v-role').forEach(b=>b.classList.toggle('selected',b.dataset.role===r));const label=roleLabel(r);const s=$('#l2vRoleStatus');if(s)s.textContent='Selected: '+label;const b=$('#l2vLogin');if(b)b.textContent='Login as '+label}
function render(){if(gate)return;hideApp();gate=document.createElement('div');gate.id='l2AuthGate';gate.innerHTML=`<div class="l2v-shell"><div class="l2v-brand"><div class="puppy">🐶</div><h1>Welcome to Cognitive Care NER</h1><p>Simple showcase login — no OTP required.</p></div><div class="l2v-card"><div class="l2v-progress"><i class="active"></i><i></i><i></i></div><div id="l2vErr" class="l2v-error" role="alert"></div><section class="l2v-step active" data-step="0"><div class="l2v-lock">🔐</div><h2>Sign in</h2><p class="hint">Choose your account type, then enter the Login ID and password provided for the showcase.</p><div class="l2v-role-picker" role="group" aria-label="Choose account role"><button type="button" class="l2v-role selected" data-role="patient"><span class="role-icon">🧠</span><strong>Patient</strong><small>Mino training &amp; progress</small></button><button type="button" class="l2v-role" data-role="caregiver"><span class="role-icon">🤝</span><strong>Caregiver / Family</strong><small>Care plan &amp; patient support</small></button><button type="button" class="l2v-role" data-role="health_worker"><span class="role-icon">🩺</span><strong>Doctor / Health Worker</strong><small>Clinical care workspace</small></button></div><div class="l2v-role-status" id="l2vRoleStatus">Selected: Patient</div><div class="l2v-field"><label for="l2vLoginId">Login ID</label><input id="l2vLoginId" autocomplete="username" placeholder="e.g. patient001"></div><div class="l2v-field"><label for="l2vPassword">Password</label><input id="l2vPassword" type="password" autocomplete="current-password" placeholder="Enter password"></div><div class="l2v-actions"><button class="l2v-btn primary" id="l2vLogin" type="button">Login as Patient</button></div><div class="l2v-note"><strong>Showcase mode:</strong> authentication is handled by the app server and the account registry. No SMS or email OTP is required.</div><div class="l2v-note"><strong>Need an account?</strong> Use one of the demo credentials supplied with this prototype. New-account creation is intentionally disabled for the showcase.</div></section></div></div>`;document.body.prepend(gate);wire()}
function wire(){gate.querySelectorAll('.l2v-role').forEach(b=>b.onclick=()=>selectRole(b.dataset.role));$('#l2vLogin').onclick=login;$('#l2vPassword').onkeydown=e=>{if(e.key==='Enter')login()}}
async function api(path,options={}){const r=await fetch(ENDPOINT+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Authentication request failed.');return d}
function saveSession(token,p){try{localStorage.setItem(TOKEN_KEY,token);localStorage.setItem('ccner.local.profile',JSON.stringify(p))}catch{}}
function clearSession(){try{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem('ccner.local.profile')}catch{}}
async function login(){msg('');const loginId=$('#l2vLoginId')?.value.trim(),password=$('#l2vPassword')?.value;if(!loginId||!password)return msg('Enter your Login ID and password.');const b=$('#l2vLogin');b.disabled=true;b.textContent='Checking…';try{const d=await api('/login',{method:'POST',body:JSON.stringify({loginId,password,role:selectedRole})});user=d.user;profile={...d.user,user_id:d.user.user_id,display_name:d.user.full_name,requested_role:d.user.role,role:d.user.role,profile_complete:true};saveSession(d.token,profile);finish()}catch(e){msg(e.message||'Login failed.')}finally{b.disabled=false;b.textContent='Login as '+roleLabel(selectedRole)}}
async function restore(){const token=localStorage.getItem(TOKEN_KEY);if(!token){render();return}try{const d=await api('/me',{headers:{Authorization:'Bearer '+token}});user=d.user;profile={...d.user,user_id:d.user.user_id,display_name:d.user.full_name,requested_role:d.user.role,role:d.user.role,profile_complete:true};finish()}catch{clearSession();render()}}
function finish(){clearSession();try{const token=arguments[0]}catch{};const tokenToKeep=window.__ccnerAuthToken;/* token is already persisted by login */try{window.CCNERAuth?.__set?.(user,profile)}catch{}gate?.remove();gate=null;if(['caregiver','health_worker'].includes(profile?.role)&&window.CCNERCareTeam)window.CCNERCareTeam.open();else showApp();window.CCNERRuleEngine?.setState({auth:'authenticated',profileComplete:true,role:profile?.role||'patient'});window.CCNERRuleEngine?.evaluate('AUTH_SUCCESS',{profileComplete:true,role:profile?.role||'patient'});window.dispatchEvent(new CustomEvent('ccner:profile-ready',{detail:{...profile,userId:user?.user_id}}))}
async function signOut(){const token=localStorage.getItem(TOKEN_KEY);try{if(token)await api('/logout',{method:'POST',headers:{Authorization:'Bearer '+token}})}catch{}clearSession();user=null;profile=null;gate?.remove();gate=null;hideApp();render()}
function client(){return null}
window.CCNERAuth={client,getProfile:()=>profile,isAuthenticated:()=>!!user,signOut,__set:(u,p)=>{user=u;profile=p}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',restore,{once:true});else restore();
})();