/* Cognitive Care NER — canonical app drawer.
 * One accessible slide-out shell for profile, dashboard, Mino, games, reminders,
 * progress, family mode, sound/accessibility, language and sign-out.
 */
(()=>{'use strict';
if(window.__CCNER_NAV_SHELL__)return;window.__CCNER_NAV_SHELL__=true;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let returnFocus=null;
const langs=()=>window.CCNERLanguageController?.getLanguages?.()||[];
const profile=()=>window.CCNERAuth?.getProfile?.()||{};
const user=()=>window.CCNERAuth?.client?.()?.auth?null:null;
function initials(p){const n=String(p.full_name||p.display_name||'User').trim().split(/\s+/).filter(Boolean);return (n[0]?.[0]||'U')+(n[1]?.[0]||'')}
function mount(){if($('#ccnerDrawer'))return;const d=document.createElement('aside');d.id='ccnerDrawer';d.className='ccner-drawer';d.hidden=true;d.setAttribute('aria-labelledby','ccnerDrawerTitle');d.innerHTML=`
<div class="ccner-drawer-backdrop" data-drawer-close></div>
<section class="ccner-drawer-panel" role="dialog" aria-modal="true" aria-labelledby="ccnerDrawerTitle">
<header class="ccner-drawer-head"><div class="ccner-profile"><div id="ccnerProfileAvatar" class="ccner-profile-avatar" aria-hidden="true">U</div><div><p class="eyebrow">COGNITIVE CARE NER</p><h2 id="ccnerDrawerTitle">You</h2><p id="ccnerProfileMeta">Your account</p></div></div><button type="button" class="ccner-drawer-close" data-drawer-close aria-label="Close menu">×</button></header>
<nav class="ccner-drawer-nav" aria-label="App menu">
<button type="button" data-drawer-action="dashboard">⌂ <span>Dashboard</span></button>
<button type="button" data-drawer-action="profile">👤 <span>Profile</span></button>
<button type="button" data-drawer-action="mino">🐶 <span>Mino</span></button>
<button type="button" data-drawer-action="games">🎮 <span>Game settings</span></button>
<button type="button" data-drawer-action="reminders">⏰ <span>Reminders</span></button>
<button type="button" data-drawer-action="progress">📈 <span>Progress</span></button>
<button type="button" data-drawer-action="family">👨‍👩‍👧 <span>Care team</span></button>
<button type="button" data-drawer-action="sound">🔊 <span>Sound & accessibility</span></button>
</nav>
<details class="ccner-drawer-section" name="drawer-settings"><summary>🌐 Language</summary><div id="ccnerLanguageList" class="ccner-language-list"></div></details>
<details class="ccner-drawer-section" name="drawer-settings"><summary>🔐 Privacy & security</summary><div class="ccner-security-box"><p>Your account uses authenticated access and protected cloud sync.</p><button type="button" data-drawer-action="security">Open privacy & security</button></div></details>
<div class="ccner-drawer-foot"><button type="button" class="ccner-signout" data-drawer-action="signout">↪ <span>Sign out</span></button><small>Training performance only. Not a diagnosis or clinical stage.</small></div>
</section></aside>`;document.body.appendChild(d);wire(d);refreshProfile();renderLanguages()}
function wire(d){d.addEventListener('click',e=>{const action=e.target.closest('[data-drawer-action]')?.dataset.drawerAction;if(action)activate(action);if(e.target.closest('[data-drawer-close]'))close()});}
function refreshProfile(){const p=profile(),a=$('#ccnerProfileAvatar'),m=$('#ccnerProfileMeta');if(a){a.textContent=initials(p);const avatar=p.avatar_url||p.photo_url||p.profile_photo;if(avatar){a.textContent='';const img=document.createElement('img');img.src=avatar;img.alt='';img.referrerPolicy='no-referrer';a.appendChild(img)}}if(m)m.textContent=p.full_name||p.display_name||'Your account'}
function renderLanguages(){const box=$('#ccnerLanguageList');if(!box)return;box.replaceChildren();const current=window.CCNERLanguageController?.getLanguage?.()||localStorage.getItem('ccner-language')||'en-IN';langs().forEach(l=>{const b=document.createElement('button');b.type='button';b.className='ccner-language-choice'+(l.id===current?' selected':'');b.dataset.lang=l.id;const name=document.createElement('span');name.textContent=l.native||l.name;const small=document.createElement('small');small.textContent=l.name;b.append(name,small);b.onclick=()=>{window.CCNERLanguageController?.setLanguage?.(l.id);renderLanguages();setTimeout(()=>{const d=$('#ccnerDrawer');if(d&&!d.hidden)close();},80)};box.appendChild(b)})}
function open(){mount();refreshProfile();renderLanguages();const d=$('#ccnerDrawer'),panel=d?.querySelector('.ccner-drawer-panel');if(!d||!panel)return;returnFocus=document.activeElement;d.hidden=false;const trigger=document.querySelector('.top-menu-trigger');trigger?.setAttribute('aria-expanded','true');trigger?.setAttribute('aria-controls','ccnerDrawer');document.body.classList.add('ccner-drawer-open');const app=$('.app-shell');if(app)app.inert=true;requestAnimationFrame(()=>panel.querySelector('[data-drawer-action="dashboard"]')?.focus())}
function close(){const d=$('#ccnerDrawer');if(!d)return;d.hidden=true;document.body.classList.remove('ccner-drawer-open');const trigger=document.querySelector('.top-menu-trigger');trigger?.setAttribute('aria-expanded','false');const app=$('.app-shell');if(app)app.inert=false;if(returnFocus?.focus)returnFocus.focus();returnFocus=null}
function overlay(title,build){const panel=$('#overlayPanel'),content=$('#overlayContent');if(!panel||!content)return;content.replaceChildren();const ey=document.createElement('p');ey.className='eyebrow';ey.textContent='MINO';const h=document.createElement('h3');h.textContent=title;content.append(ey,h);build(content);panel.hidden=false;$('#closeOverlay')?.focus()}
function button(label,fn){const b=document.createElement('button');b.type='button';b.className='action-button';b.textContent=label;b.onclick=fn;return b}
function ageFromDob(dob){if(!dob)return'';const d=new Date(dob+'T00:00:00'),n=new Date();if(Number.isNaN(d.getTime()))return'';let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a>=0&&a<130?String(a):''}
function readBasic(p){try{const local=JSON.parse(localStorage.getItem('ccner-basic-patient-profile')||'{}');return {...(p?.basic_patient_info||{}),...local}}catch(_){return {...(p?.basic_patient_info||{})}}}
function profilePanel(){
 const p=profile(),sb=window.CCNERAuth?.client?.(),info=readBasic(p);
 overlay('Patient Profile',c=>{
  const root=document.createElement('div');root.className='ccner-patient-profile';
  const head=document.createElement('div');head.className='ccner-patient-profile-head';
  const title=document.createElement('div');title.innerHTML='<span class="ccner-profile-kicker">BASIC PATIENT INFORMATION</span><h4>Personal, health & care details</h4><p>Information you or your family can provide. No clinical diagnosis fields.</p>';
  const edit=button('Edit profile',()=>renderProfileEditor(root,p,root._patientInfo||info,sb));edit.classList.add('ccner-profile-edit');
  head.append(title,edit);root.append(head);root._patientInfo=info;
  renderProfileSummary(root,p,info);c.append(root,button('Close',()=>window.CCNERUI?.closeOverlay?.()));loadRemoteBasic(root,p,info,sb);
 })
}
async function loadRemoteBasic(root,p,info,sb){
 if(!sb||!p?.user_id)return;
 try{const [{data,error},{data:authData}]=await Promise.all([sb.from('profiles').select('basic_patient_info,full_name,display_name,date_of_birth,gender,preferred_language,emergency_contact,emergency_relationship,caregiver_name,region').eq('user_id',p.user_id).maybeSingle(),sb.auth.getUser()]);if(error||!data)return;const fresh={...info,...(data.basic_patient_info||{})};if(authData?.user?.id===p.user_id){fresh.phone=fresh.phone||authData.user.phone||'';fresh.email=fresh.email||authData.user.email||''}localStorage.setItem('ccner-basic-patient-profile',JSON.stringify(fresh));root._patientInfo=fresh;root.querySelector('.ccner-profile-summary')?.replaceWith(buildProfileSummary(p,fresh));}catch(_){}
}
function row(label,value){const e=document.createElement('div');e.className='ccner-profile-data-row';const a=document.createElement('span');a.textContent=label;const b=document.createElement('strong');b.textContent=value||'Not provided';e.append(a,b);return e}
function section(title,items){const s=document.createElement('section');s.className='ccner-profile-section';const h=document.createElement('h5');h.textContent=title;s.append(h);items.forEach(x=>s.append(row(x[0],x[1])));return s}
function buildProfileSummary(p,info){
 const wrap=document.createElement('div');wrap.className='ccner-profile-summary';const basicLang=info.language||p.preferred_language||'English';
 wrap.append(section('Personal information',[['Full name',p.full_name||p.display_name],['Date of birth',info.date_of_birth||p.date_of_birth],['Age',ageFromDob(info.date_of_birth||p.date_of_birth)],['Gender',info.gender||p.gender],['Preferred language',basicLang],['Phone',info.phone],['Email',info.email],['Address',info.address],['City / district',info.city]]),section('Basic health information',[['Blood group',info.blood_group],['Known allergies',info.allergies],['Existing health conditions',info.health_conditions],['Current medicines',info.current_medications],['Past major surgery / hospitalization',info.past_surgery_hospitalization]]),section('Emergency contact',[['Name',info.emergency_name],['Relationship',info.emergency_relationship||p.emergency_relationship],['Phone',info.emergency_phone||p.emergency_contact],['Alternate phone',info.emergency_alt_phone]]),section('Care information',[['Living with',info.living_with],['Primary caregiver',info.caregiver_name||p.caregiver_name],['Caregiver phone',info.caregiver_phone],['Mobility',info.mobility],['Communication preference',info.communication_preference]]),section('Memory & cognitive concerns',[['Memory concerns',info.memory_concerns],['Remembering recent events',info.recent_memory_difficulty],['Managing daily activities',info.daily_activity_difficulty],['Other concern',info.other_concerns]]));return wrap
}
function renderProfileSummary(root,p,info){root.append(buildProfileSummary(p,info))}
function inputField(labelText,key,value,type='text',opts={}){const w=document.createElement('label');w.className='ccner-profile-field';const l=document.createElement('span');l.textContent=labelText;let e;if(opts.select){e=document.createElement('select');opts.select.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;e.append(o)});e.value=value||''}else{e=document.createElement('input');e.type=type;e.value=value||'';if(opts.readonly)e.readOnly=true;if(opts.placeholder)e.placeholder=opts.placeholder}e.dataset.profileKey=key;w.append(l,e);return w}
function textField(labelText,key,value,placeholder=''){const w=document.createElement('label');w.className='ccner-profile-field ccner-profile-wide';const l=document.createElement('span');l.textContent=labelText;const e=document.createElement('textarea');e.rows=3;e.value=value||'';e.placeholder=placeholder;e.dataset.profileKey=key;w.append(l,e);return w}
function renderProfileEditor(root,p,info,sb){
 root.querySelector('.ccner-profile-summary')?.remove();const form=document.createElement('form');form.className='ccner-profile-editor';const fields=document.createElement('div');fields.className='ccner-profile-form-grid';const add=x=>fields.append(x);
 add(inputField('Full name','full_name',p.full_name||p.display_name));add(inputField('Date of birth','date_of_birth',info.date_of_birth||p.date_of_birth,'date'));add(inputField('Age','age',ageFromDob(info.date_of_birth||p.date_of_birth),'text',{readonly:true}));add(inputField('Gender','gender',info.gender||p.gender,'text',{select:[['','Prefer not to say'],['Female','Female'],['Male','Male'],['Other','Other'],['Prefer not to say','Prefer not to say']]}));add(inputField('Preferred language','language',info.language||p.preferred_language||'en-IN','text',{select:[['en-IN','English'],['hi-IN','Hindi'],['bn-IN','Bengali'],['as-IN','Assamese']]}));add(inputField('Phone','phone',info.phone,'tel',{readonly:true}));add(inputField('Email','email',info.email,'email',{readonly:true}));add(inputField('Address','address',info.address));add(inputField('City / district','city',info.city));form.append(titleBlock('Personal information'),fields);
 const health=document.createElement('div');health.className='ccner-profile-form-grid';[['Blood group','blood_group'],['Known allergies','allergies'],['Existing health conditions','health_conditions'],['Current medicines','current_medications'],['Past major surgery / hospitalization','past_surgery_hospitalization']].forEach(([l,k])=>health.append(textField(l,k,info[k],k==='allergies'?'Example: medicine or food allergy':'Optional'));form.append(titleBlock('Basic health information'),health);
 const emergency=document.createElement('div');emergency.className='ccner-profile-form-grid';[['Contact name','emergency_name'],['Relationship','emergency_relationship'],['Phone','emergency_phone'],['Alternate phone','emergency_alt_phone']].forEach(([l,k])=>emergency.append(inputField(l,k,info[k]||((k==='emergency_phone')?p.emergency_contact:(k==='emergency_relationship'?p.emergency_relationship:'')),'text'));form.append(titleBlock('Emergency contact'),emergency);
 const care=document.createElement('div');care.className='ccner-profile-form-grid';care.append(inputField('Living with','living_with',info.living_with,'text',{select:[['','Choose'],['Alone','Alone'],['Family','Family'],['Caregiver','Caregiver']]}));care.append(inputField('Primary caregiver','caregiver_name',info.caregiver_name||p.caregiver_name));care.append(inputField('Caregiver phone','caregiver_phone',info.caregiver_phone,'tel'));care.append(inputField('Mobility','mobility',info.mobility,'text',{select:[['','Choose'],['Independent','Independent'],['Needs some assistance','Needs some assistance'],['Needs significant assistance','Needs significant assistance']]}));care.append(inputField('Communication preference','communication_preference',info.communication_preference,'text',{select:[['','Choose'],['Normal conversation','Normal conversation'],['Needs simple instructions','Needs simple instructions'],['Needs assistance','Needs assistance']]}));form.append(titleBlock('Care information'),care);
 const memory=document.createElement('div');memory.className='ccner-profile-form-grid';memory.append(inputField('Memory concerns','memory_concerns',info.memory_concerns,'text',{select:[['','Choose'],['No','No'],['Sometimes','Sometimes'],['Frequently','Frequently']]}));memory.append(inputField('Remembering recent events','recent_memory_difficulty',info.recent_memory_difficulty,'text',{select:[['','Choose'],['No difficulty','No difficulty'],['Sometimes difficult','Sometimes difficult'],['Frequently difficult','Frequently difficult']]}));memory.append(inputField('Managing daily activities','daily_activity_difficulty',info.daily_activity_difficulty,'text',{select:[['','Choose'],['Independent','Independent'],['Sometimes difficult','Sometimes difficult'],['Needs assistance','Needs assistance']]}));memory.append(textField('Other concern','other_concerns',info.other_concerns,'Optional — patient/family can describe the concern'));form.append(titleBlock('Memory & cognitive concerns'),memory);
 const actions=document.createElement('div');actions.className='ccner-profile-form-actions';const cancel=button('Cancel',()=>{form.replaceWith(buildProfileSummary(p,root._patientInfo||info));});const save=button('Save profile',async()=>saveProfile(form,p,sb,root));save.classList.add('primary');actions.append(cancel,save);form.append(actions);root.append(form);form.querySelector('[data-profile-key="date_of_birth"]')?.addEventListener('change',e=>{const a=form.querySelector('[data-profile-key="age"]');if(a)a.value=ageFromDob(e.target.value)});
}
function titleBlock(title){const h=document.createElement('h5');h.className='ccner-profile-form-title';h.textContent=title;return h}
async function saveProfile(form,p,sb,root){
 const data={};form.querySelectorAll('[data-profile-key]').forEach(e=>{if(e.dataset.profileKey!=='age')data[e.dataset.profileKey]=String(e.value||'').trim()});const payload={full_name:data.full_name||null,display_name:data.full_name||null,date_of_birth:data.date_of_birth||null,gender:data.gender||null,preferred_language:data.language||'en-IN',emergency_contact:data.emergency_phone||null,emergency_relationship:data.emergency_relationship||null,caregiver_name:data.caregiver_name||null,profile_complete:true};if(!payload.full_name){alert('Please enter the full name.');return}const merged={...readBasic(p),...data,updated_at:new Date().toISOString()};let saved=false;
 if(sb&&p?.user_id){try{const {data:updated,error}=await sb.from('profiles').update({...payload,basic_patient_info:merged}).eq('user_id',p.user_id).select('*').single();if(error)throw error;Object.assign(p,updated||{});localStorage.setItem('ccner-basic-patient-profile',JSON.stringify(merged));root._patientInfo=merged;saved=true}catch(e){alert(e?.message||'Could not save to the secure profile. Your changes are kept on this device.')}}
 if(!saved){Object.assign(p,payload,{basic_patient_info:merged});localStorage.setItem('ccner-basic-patient-profile',JSON.stringify(merged));root._patientInfo=merged}
 root.querySelector('.ccner-profile-editor')?.replaceWith(buildProfileSummary(p,root._patientInfo));refreshProfile();alert(saved?'Patient profile saved.':'Saved on this device; secure sync will retry when available.');
}
function openMino(){if(window.CCNERLevel3?.openMino)return window.CCNERLevel3.openMino();minoPanel()}function minoPanel(){overlay('Mino settings',c=>{const row=document.createElement('div');row.className='setting-row';const s=document.createElement('span');s.textContent='🔊 Mino voice';const b=button(window.state?.soundOn===false?'Off':'On',()=>{$('#soundToggle')?.click();b.textContent=window.state?.soundOn===false?'Off':'On'});row.append(s,b);const row2=document.createElement('div');row2.className='setting-row';const a=document.createElement('span');a.textContent='🎙️ Live voice';const live=button(window.CCNERMinoLive?.isRunning?.()?'Stop':'Start',()=>{if(window.CCNERMinoLive?.isRunning?.()){window.CCNERMinoLive.stop();live.textContent='Start'}else{window.CCNERMinoLive?.start?.();live.textContent='Stop'}});row2.append(a,live);c.append(row,row2)})}
function gamePanel(){overlay('Game settings',c=>{const keys=[['ccner-game-sound','Game sounds'],['ccner-game-hints','Gentle hints'],['ccner-game-large','Large game controls']];keys.forEach(([k,label])=>{const row=document.createElement('label');row.className='setting-row';const s=document.createElement('span');s.textContent=label;const i=document.createElement('input');i.type='checkbox';i.checked=localStorage.getItem(k)!=='off';i.onchange=()=>localStorage.setItem(k,i.checked?'on':'off');row.append(s,i);c.append(row)})})}
async function familyPanel(){const p=profile();if(['caregiver','health_worker'].includes(p.role))return window.CCNERCareTeam?.open?.();overlay('Care team',async c=>{const intro=document.createElement('p');intro.textContent='Share your Care Code with a trusted caregiver or doctor. You stay in control and can revoke access at any time.';const code=document.createElement('div');code.className='ccner-care-code';code.textContent=p?.user_id||'Sign in to view your Care Code';const note=document.createElement('p');note.className='overlay-note';note.textContent='Care Code: share only with someone you trust. It is a pairing identifier, not a password.';c.append(intro,code,note);const sb=window.CCNERAuth?.client?.();if(!sb||!p?.user_id)return;const {data}=await sb.from('caregiver_links').select('id,caregiver_user_id,role,status,created_at').eq('patient_user_id',p.user_id).eq('status','active').order('created_at',{ascending:false});const h=document.createElement('h4');h.textContent='Active connections';c.append(h);if(!data?.length){const e=document.createElement('p');e.className='overlay-note';e.textContent='No caregiver or doctor is connected yet.';c.append(e);return}data.forEach(x=>{const row=document.createElement('div');row.className='setting-row';const text=document.createElement('span');text.textContent=(x.role==='health_worker'?'Doctor / Health Worker':'Caregiver')+' · '+String(x.caregiver_user_id).slice(0,8)+'…';const b=button('Revoke',async()=>{const r=await sb.from('caregiver_links').update({status:'revoked',updated_at:new Date().toISOString()}).eq('id',x.id).eq('patient_user_id',p.user_id);if(r.error)return alert(r.error.message);row.remove()});row.append(text,b);c.append(row)})})}
function soundPanel(){overlay('Sound & accessibility',c=>{const row=document.createElement('div');row.className='setting-row';const s=document.createElement('span');s.textContent='Mino voice';const b=button(window.state?.soundOn===false?'Off':'On',()=>$('#soundToggle')?.click());row.append(s,b);const p=document.createElement('p');p.className='overlay-note';p.textContent='Your selected language is also used for speech input when the device supports it.';c.append(row,p)})}
function activate(action){close();if(action==='dashboard'){if(['caregiver','health_worker'].includes(profile().role))return window.CCNERCareTeam?.open?.();return window.CCNERUI?.home?.();}if(action==='profile')return profilePanel();if(action==='mino')return openMino();if(action==='games')return gamePanel();if(action==='reminders')return window.CCNERUI?.reminders?.();if(action==='progress')return window.CCNERUI?.progress?.();if(action==='family')return familyPanel();if(action==='sound')return soundPanel();if(action==='security')return window.CCNERSecurity?.open?.();if(action==='signout')return window.CCNERAuth?.signOut?.()}
window.CCNERNavigation={open,close,home:()=>window.CCNERUI?.home?.(),progress:()=>window.CCNERUI?.progress?.(),reminders:()=>window.CCNERUI?.reminders?.(),mino:openMino,settings:open,refresh:()=>{refreshProfile();renderLanguages()}};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#ccnerDrawer')?.hidden)close()});
window.addEventListener('ccner:profile-ready',()=>{refreshProfile();renderLanguages()});
window.addEventListener('ccner:language-change',()=>renderLanguages());
document.addEventListener('DOMContentLoaded',mount,{once:true});if(document.readyState!=='loading')mount();
})();