const http = require('http');
const fs = require('fs');
const path = require('path');
const PORT = Number(process.env.PORT || 80);
const ROOT = path.join(__dirname, 'prototype', 'phase-0');
const MAX_BODY = 12000;
const AI_WINDOW_MS = 60_000;
const AI_LIMIT = Number(process.env.AI_RATE_LIMIT || 20);
const rate = new Map();
const MIME = {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml'};
function headers(type,cache='no-store',extra={}){return {'Content-Type':type,'Cache-Control':cache,'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), geolocation=(), payment=(), usb=()','Access-Control-Allow-Origin':process.env.CORS_ORIGIN||'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type',...extra}}
function send(res,status,type,body,cache='no-store'){res.writeHead(status,headers(type,cache));res.end(body)}
function readBody(req){return new Promise((resolve,reject)=>{let body='';req.on('data',c=>{body+=c;if(body.length>MAX_BODY){req.destroy();reject(new Error('body too large'))}});req.on('end',()=>resolve(body));req.on('error',reject)})}
function allowed(req){const ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();const now=Date.now();let x=rate.get(ip);if(!x||now-x.started>AI_WINDOW_MS)x={started:now,count:0};x.count++;rate.set(ip,x);if(rate.size>5000)for(const [k,v] of rate)if(now-v.started>AI_WINDOW_MS)rate.delete(k);return x.count<=AI_LIMIT}
async function chat(req,res){
 if(!allowed(req))return send(res,429,'application/json; charset=utf-8',JSON.stringify({error:'Too many AI requests. Please wait a moment.'}));
 if(!process.env.OPENAI_API_KEY)return send(res,503,'application/json; charset=utf-8',JSON.stringify({error:'AI is not configured on this deployment'}));
 try{const body=JSON.parse(await readBody(req));const message=String(body.message||'').slice(0,2000);const history=Array.isArray(body.history)?body.history.slice(-8):[];const locale=String(body.language||'en-IN').slice(0,20);const languageName=String(body.languageName||'').slice(0,40);const context=`Current screen: ${body.screen||'homeView'}\nCurrent game: ${body.game||'none'}\nAdaptive training level: ${body.level||1}`;const languageInstruction=locale==='en-IN'?'Respond in English.':`Respond naturally in ${languageName||locale}. Preserve simple, elderly-friendly language and use the selected language consistently.`;const instructions=`You are Momo, a warm, playful AI companion inside Cognitive Care NER, an elderly-friendly cognitive training app for people in the North Eastern Region of India. Be natural, varied, encouraging and concise. Speak like a friendly pet companion, not a clinical assistant. Use simple language and occasional gentle humor. Never diagnose dementia, never interpret a game score as a medical diagnosis, and never invent clinical conclusions. If the user asks to start/play a game, the app handles that action; your job is to encourage them. Keep replies to 1-3 short sentences. ${languageInstruction} ${context}`;const input=[...history.map(x=>({role:x.role==='assistant'?'assistant':'user',content:String(x.text||'').slice(0,2000)})),{role:'user',content:message}];const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',instructions,input,store:false,max_output_tokens:180})});const data=await r.json();if(!r.ok)return send(res,r.status,'application/json; charset=utf-8',JSON.stringify({error:data?.error?.message||'AI request failed'}));const reply=data.output_text||((data.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||'').filter(Boolean).join(' '));if(!reply)return send(res,502,'application/json; charset=utf-8',JSON.stringify({error:'AI returned no text'}));return send(res,200,'application/json; charset=utf-8',JSON.stringify({reply}))}catch(e){return send(res,400,'application/json; charset=utf-8',JSON.stringify({error:e.message||'Bad request'}))}}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,headers('text/plain; charset=utf-8'));return res.end()}if(req.method==='GET'&&req.url==='/health')return send(res,200,'text/plain; charset=utf-8','ok\n','no-store');if(req.method==='POST'&&req.url==='/api/chat')return chat(req,res);if(req.method!=='GET'&&req.method!=='HEAD')return send(res,405,'text/plain; charset=utf-8','Method Not Allowed');let urlPath=decodeURIComponent((req.url||'/').split('?')[0]);if(urlPath==='/')urlPath='/index.html';const file=path.normalize(path.join(ROOT,urlPath));if(!file.startsWith(ROOT))return send(res,403,'text/plain; charset=utf-8','Forbidden');fs.readFile(file,(err,data)=>{if(err)return send(res,404,'text/plain; charset=utf-8','Not Found');const type=MIME[path.extname(file).toLowerCase()]||'application/octet-stream';res.writeHead(200,headers(type,'no-cache'));if(req.method!=='HEAD')res.end(data);else res.end()})});
server.listen(PORT,'0.0.0.0',()=>console.log(`Cognitive Care NER listening on ${PORT}`));
