/* Security & privacy center: consent, audit trail, export and app-data deletion. */
(function(){
  'use strict';
  const KEY='ccner-security-center';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return{}}};
  const write=v=>localStorage.setItem(KEY,JSON.stringify(v));
  const state=Object.assign({consentAccepted:false,analytics:false,notifications:false,privacyVersion:'1.0',lastAuditAt:null},read());
  function save(){write(state)}
  async function audit(action,metadata={}){state.lastAuditAt=new Date().toISOString();save();window.CCNERProduction?.recordSafetyEvent?.(action,JSON.stringify(metadata));await window.CCNERProductionHardening?.audit?.(action,metadata)}
  async function setConsent(name,value){state[name]=!!value;state.consentAccepted=state.consentAccepted||!!value;save();await audit('consent.changed',{name,value,privacyVersion:state.privacyVersion});try{const C=window.CCNER_CONFIG||{};const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');const sb=mod.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);const s=await sb.auth.getSession();if(s.data?.session?.user){await sb.from('notification_preferences').upsert({user_id:s.data.session.user.id,push_enabled:!!state.notifications,reminder_enabled:true,updated_at:new Date().toISOString()},{onConflict:'user_id')}}}catch(_){} }
  function exportLocal(){const keys=['ccner-p1-profile','ccner-p1-reminders','ccner-p1-tasks','ccner-p1-sync','ccner-history','ccner_phase4','ccner-adaptive-ml-v1','ccner-usability-validation'];const out={exportedAt:new Date().toISOString(),privacyVersion:state.privacyVersion};keys.forEach(k=>{try{out[k]=JSON.parse(localStorage.getItem(k)||'null')}catch(_){out[k]=null}});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download='cognitive-care-ner-personal-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);audit('data.exported',{scope:'local'})}
  async function deleteCloud(){const C=window.CCNER_CONFIG||{};try{const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');const sb=mod.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);const s=await sb.auth.getSession();const uid=s.data?.session?.user?.id;if(!uid)throw new Error('Sign in required for cloud deletion');await sb.from('game_results').delete().eq('user_id',uid);await sb.from('caregiver_alerts').delete().eq('patient_id',uid);await sb.from('daily_tasks').delete().eq('user_id',uid);await sb.from('reminders').delete().eq('user_id',uid);await sb.from('training_baselines').delete().eq('user_id',uid);await sb.from('sync_queue').delete().eq('user_id',uid);await sb.from('sync_events').delete().eq('user_id',uid);await sb.from('cognitive_sessions').delete().eq('user_id',uid);await sb.from('notification_preferences').delete().eq('user_id',uid);await sb.from('profiles').delete().eq('user_id',uid);await audit('data.deleted',{scope:'cloud_app_data'});return true}catch(e){alert(e.message||'Cloud data deletion failed.');return false}}
  async function deleteAll(){if(!confirm('Delete this app data from this device and, if signed in, from cloud storage? This cannot be undone.'))return;await deleteCloud();['ccner-p1-profile','ccner-p1-reminders','ccner-p1-tasks','ccner-p1-sync','ccner-history','ccner_phase4','ccner-adaptive-ml-v1','ccner-usability-validation','ccner-p2-session-sync','ccner-p2-sync-complete'].forEach(k=>localStorage.removeItem(k));location.reload()}
  function render(){const s=read();return `<div class="ph-card"><h3>Privacy & security</h3><p class="p1-muted">Your training data is used for personalization and progress tracking. Game scores are training performance, not a medical diagnosis.</p><div class="ph-row"><div><strong>Training analytics</strong><small>Save progress and caregiver analytics.</small></div><button class="ph-btn secondary" data-sec="analytics">${s.analytics?'Enabled':'Enable'}</button></div><div class="ph-row"><div><strong>Reminder notifications</strong><small>Allow scheduled reminder delivery.</small></div><button class="ph-btn secondary" data-sec="notifications">${s.notifications?'Enabled':'Enable'}</button></div><div class="ph-actions"><button class="ph-btn" data-sec="export">Export my data</button><button class="ph-btn secondary" data-sec="audit">Security activity</button><button class="ph-btn secondary" data-sec="delete">Delete app data</button></div></div>`}
  function open(){let p=document.getElementById('securityCenter');if(!p){p=document.createElement('section');p.id='securityCenter';p.className='p2-panel';document.body.appendChild(p)}p.innerHTML='<div class="p2-sheet"><button class="p2-close" aria-label="Close">×</button><span class="p2-eyebrow">PRIVACY & SECURITY</span><h2>Your data controls</h2>'+render()+'</div>';p.querySelector('.p2-close').onclick=()=>p.remove();p.querySelectorAll('[data-sec]').forEach(b=>b.onclick=async()=>{const a=b.dataset.sec;if(a==='analytics'){await setConsent('analytics',!read().analytics);open()}else if(a==='notifications'){const ok=await window.CCNERNotifications?.request?.();if(ok)await setConsent('notifications',true);open()}else if(a==='export')exportLocal();else if(a==='delete')await deleteAll();else if(a==='audit')alert(window.CognitiveCareProduction?.exportAudit?.()||'No local security activity yet.')})}
  function boot(){const home=document.getElementById('homeView');if(!home||document.getElementById('securityCenterButton'))return;const b=document.createElement('button');b.id='securityCenterButton';b.className='p2-btn p2-dashboard-launch';b.textContent='🔐 Privacy & security';b.onclick=open;home.appendChild(b)}
  window.CCNERSecurity={open,setConsent,exportLocal,deleteAll};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
